name: static code analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
    branches:
      - main

jobs:
  build-test:
    name: Build & Test,
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.0"
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build .
      - name: Run testing
        run: go test ./... -v

  static-code-analysis:
    name: Static Code Analysis,
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Revive static code analysis
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
          path: "./..."
